[project]
name = "linux-autoruns"
version = "2.5.0"
description = "Autoruns program for linux."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyside6>=6.11.2",
]

[project.optional-dependencies]
test = [
    "pytest>=8.0",
]

[project.scripts]
linux-autoruns = "linux_autoruns:main"

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
